language: php

php:
  - 5.5
  - 5.6
  - 7

services:
  - mysql
  - postgresql

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.5.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.0.5/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --noauth &> /dev/null &

before_script:
  - if [ $TRAVIS_PHP_VERSION != "7" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ $TRAVIS_PHP_VERSION == "7" ]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES
  - psql -c 'create database event_store_adapter_benchmarks;' -U postgres
  - mysql -e 'create database event_store_adapter_benchmarks;'

script:
  - php ./bin/run_benchmark.php
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
